# Generated by Django 6.0.3 on 2026-04-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_track_genre_dislike_like_track_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='artists/'),
        ),
    ]
